jumain_health_homepage:
    path:     /
    defaults: { _controller: JUMAINHealthBundle:Default:index }

jumain_health_child_entered_by_date:
    path:     /ChldEntrdByDate/{dateValue}
    defaults: { _controller: JUMAINHealthBundle:Default:getChildEnteredByDate }
    methods:   [GET]
    requirements:
        dateValue: \d+

jumain_health_num_child_entered_by_date:
    path:     /NumChldEntrdByDate/{dateValue}
    defaults: { _controller: JUMAINHealthBundle:Default:getNumChildEnteredByDate }
    methods:   [GET]

jumain_health_tot_num_child_entered_till_date:
    path:     /TotNumChildTillDate/{dateValue}
    defaults: { _controller: JUMAINHealthBundle:Default:getTotNumChildEnteredTillDate }
    methods:   [GET]

jumain_health_homepage:
    path:     /
    defaults: { _controller: JUMAINHealthBundle:Default:index }

jumain_health_homepage:
    path:     /
    defaults: { _controller: JUMAINHealthBundle:Default:index }

jumain_health_homepage:
    path:     /
    defaults: { _controller: JUMAINHealthBundle:Default:index }

jumain_health_homepage:
    path:     /
    defaults: { _controller: JUMAINHealthBundle:Default:index }

jumain_consumer_api_musvids_local:
    path:     /musvids/local
    defaults: { _controller: JUMAINConsumerApiBundle:Default:getLocalMusVids }
    methods:   [GET]

jumain_consumer_api_musvids_foreign:
    path:     /musvids/foreign
    defaults: { _controller: JUMAINConsumerApiBundle:Default:getForeignMusVids }
    methods:   [GET]

jumain_consumer_api_trailers_local:
    path:     /trailers/local
    defaults: { _controller: JUMAINConsumerApiBundle:Default:getLocalTrailers }
    methods:   [GET]

jumain_consumer_api_trailers_foreign:
    path:     /trailers/foreign
    defaults: { _controller: JUMAINConsumerApiBundle:Default:getForeignTrailers }
    methods:   [GET]

jumain_consumer_api_channels:
    path:     /channels
    defaults: { _controller: JUMAINConsumerApiBundle:Default:getChannels }
    methods:   [GET]

jumain_consumer_api_channel_videos:
    path:     /channels/{id}/channelvideos
    defaults: { _controller: JUMAINConsumerApiBundle:Default:getChannelVideos }
    methods:   [GET]
    requirements:
        channelId: \d+