<?php

namespace JUMAIN\AdminBundle\Repository;

/**
 * NormalUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NormalUserRepository extends \Doctrine\ORM\EntityRepository
{
}
