<?php

namespace JUMAIN\HealthBundle\Repository;

/**
 * MedicalDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
