<?php

namespace JUMAIN\HealthBundle\Repository;

/**
 * CommunityInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityRepository extends \Doctrine\ORM\EntityRepository
{
}
