<?php

namespace JUMAIN\HealthBundle\Repository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllChildEnteredByDate($dateValue){
		$realDate = new  \DateTime($dateValue);

    $patients = $this->getEntityManager()
                    ->createQuery(
                    'SELECT p FROM JUMAINHealthBundle:Patient p
                    WHERE ( p.detail.vaccinationDate = :dateVal)
                    ORDER BY p.detail.vaccinationDate ASC ')
                    ->setParameters(array('dateVal' => $realDate,))
                    ->getResult();
    return $patients;
  }

  public function findNumChildEnteredByDate($dateValue){
  	$realDate = new  \DateTime($dateValue);

    $countChild = $this->getEntityManager()
                    ->createQuery(
                    'SELECT COUNT(p.id) FROM JUMAINHealthBundle:Patient p
                    WHERE ( p.detail.vaccinationDate = :dateVal)
                    ORDER BY p.detail.vaccinationDate ASC ')
                    ->setParameters(array('dateVal' => $realDate,))
                    ->getSingleScalarResult();
    return $countChild;
  }

  public function findTotNumChildEnteredTillDate($dateValue){
  	$realDate = new  \DateTime($dateValue);

    $countAllChild = $this->getEntityManager()
                    ->createQuery(
                    'SELECT COUNT(p.id) FROM JUMAINHealthBundle:Patient p
                    WHERE ( p.detail.vaccinationDate <= :dateVal)
                    ORDER BY p.detail.vaccinationDate ASC ')
                    ->setParameters(array('dateVal' => $realDate,))
                    ->getSingleScalarResult();
    return $countAllChild;
  }

  public function findAllRegPatients(){
    $patients = $this->getEntityManager()
                    ->createQuery(
                    'SELECT p FROM JUMAINHealthBundle:Patient p
                    ORDER BY p.createdAt ASC ')
                    ->getResult();
    return $patients;
  }
}
