<?php

namespace JUMAIN\HealthBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllRegProjects(){
    $projects = $this->getEntityManager()
                    ->createQuery(
                    'SELECT p FROM JUMAINHealthBundle:Project p
                    ORDER BY p.projectName ASC ')
                    ->getResult();
    return $projects;
  }
}
